steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "--tag=gcr.io/${GOOGLE_CLOUD_PROJECT}/stories:latest",
        --build-arg API_URL="https://stories-621003290739.europe-west3.run.app/"',
        ".",
      ]
