substitutions:
  _API_URL: API_URL=https://stories-621003290739.europe-west3.run.app/api

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/stories:latest"
      - "--build-arg=${_API_URL}"
      - "."

images:
  - "gcr.io/$PROJECT_ID/stories:latest"
